### PR TITLE
docs: Added links to llama.cpp REST API documentation

### PR DESCRIPTION
**Pull request by josiahbryan**
docs: Added links to llama.cpp REST API documentation and fixed a small spelling error in the readme.

(Submitting PR per @ericcurtin at https://github.com/containers/ramalama/issues/265#issuecomment-2402510416)

### CODE REVIEW

**Comment by ericcurtin** [comment]
The failure is because you didn't sign your commit, please amend your commits with:

git commit -s --amend

I really wish we had a bot that delivered this feedback on failed DCO build, this happens all the time

**Comment by josiahbryan** [comment]
Just did the `git commit -s --amend` and found I had to force-update the branch - hope that did everything correctly! Thanks @ericcurtin  - let's see what happens when DCO tries again here shortly lol

**Comment by rhatdan** [comment]
Could you rebase this, then the CI/CD system will be fixed.

git pull origin main
git commit -a --amend -s
git push --force

**Comment by josiahbryan** [comment]
@ericcurtin I think I got it all resolved - should be good to go now.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Thanks @josiahbryan

**Pull request merged**
