### PR TITLE
Kompute Containerfile

### PR DESCRIPTION
**Pull request by ericcurtin**
Getting this build and pushed so we can use for testing.

Co-authored-by: Sergio Lopez <slp@redhat.com>
Signed-off-by: Eric Curtin <ecurtin@redhat.com>

### CODE REVIEW

**Comment by ericcurtin** [comment]
Trying to split out the Containerfile part of:

https://github.com/containers/ramalama/pull/235

and get that part done.

**Comment by ericcurtin** [comment]
It's named ramalama for now, although it's tempting to call it kompute because we want to merge the other vulkan implementation also and somehow portray that both images can use vulkan

**Comment by rhatdan** [comment]
@ericcurtin needs a rebase.

**Comment by ericcurtin** [comment]
@rhatdan rebased... Might as well get this in before we do a multi-arch rebuild for granitemoe support I guess...

**Pull request merged**
