### PR TITLE
Enable resumable downloads in ollama.py

### LINKED ISSUE #258: resumable downloads via ollama
When downloading huge models > 10 GB , it's not uncommon for the download to fail before it's fully downloaded.

In our client when this happens one must download the whole model from the start which is frustrating.

In Ollama client, the download can be resumed, rather than being fully downloaded again.

This can make some larger models on Ollama registry almost impossible to download via ramalama client.

### PR DESCRIPTION
**Pull request by swarajpande5**
Resolves #258 

Example run: 
```
(venv) spande-mac:ramalama (resumable-ollama-pulls*) $ ./bin/ramalama pull ollama://llama3.2:1b
Warning: podman needs to be configured to use krunkit for AI Workloads,
running without containers

Pulling rary/llama3.2/1b: 100% ▕####################▏ 861/861 3.40MB/s 00:00
Pulling d54c02d2e1b1118d: 100% ▕####################▏ 485/485 547kB/s 00:00
Pulling bed452548fa88d45:   7% ▕#4                  ▏ 92.9M/1.23G 3.68MB/s 05:32^C 


(venv) spande-mac:ramalama (resumable-ollama-pulls*) $ ./bin/ramalama pull ollama://llama3.2:1b
Warning: podman needs to be configured to use krunkit for AI Workloads,
running without containers

Manifest file /Users/spande/.local/share/ramalama/repos/ollama/manifests/https://registry.ollama.ai/library/llama3.2/1b seems corrupted, deleting and retrying download.
Pulling rary/llama3.2/1b: 100% ▕####################▏ 861/861 1.90MB/s 00:00
File https://registry.ollama.ai/v2/library/llama3.2/blobs/sha256:4f659a1e86d7f5a33c389f7991e7224b7ee6ad0358b53437d54c02d2e1b1118d already fully downloaded.
Pulling bed452548fa88d45:  10% ▕#9                  ▏ 122M/1.23G 3.44MB/s 05:47^C
```

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
We should also do checksum checking before we star the download and after. We used to do this when using curl, but it got removed, before we start the download, check via verify_checksum function.

If the checksum is good we are fully downloaded and complete no need to do anything.

Then we should attempt to download from scratch or resume a download.

Once we have downloaded we should verify_checksum again. If that checksum is incorrect we should delete the file and fail OR automatically start the download from the start again. Maybe automatically restarting the download is better.

**Comment by swarajpande5** [comment]
@ericcurtin Sure, I'll add in the checksum check as well.

**Comment by ericcurtin** [comment]
This error message isn't right and I doubt we were corrupted here:

```
$ bin/ramalama --container run llama3.2:3b
Manifest file /var/lib/ramalama/repos/ollama/manifests/https://registry.ollama.ai/library/llama3.2/3b seems corrupted, deleting and retrying download.
Pulling rary/llama3.2/3b: 100% ▕####################▏ 0.98k/0.98k 398kB/s 00:00
File https://registry.ollama.ai/v2/library/llama3.2/blobs/sha256:34bb5ab01051a11372a91f95f3fbbc51173eed8e7f13ec395b9ae9b8bd0e242b already fully downloaded.
Pulling f7da77af9f7ccdff:   5% ▕#                   ▏ 102M/1.88G 3.74MB/s 0
```

**Comment by swarajpande5** [comment]
@ericcurtin I was getting json.JSONDecodeError in the very first manifest, when I resume the downloads. 
Shall I remove the message for now ?

**Comment by ericcurtin** [comment]
Well at a minimum, this string could be corrected "/var/lib/ramalama/repos/ollama/manifests/https://registry.ollama.ai/library/llama3.2/3b"

**Comment by ericcurtin** [comment]
Tbh I don't think we need to store these files at all:

~/.local/share/ramalama/repos/ollama/manifests

**Comment by swarajpande5** [comment]
Sure, I'll correct the string

**Pull request merged**
