### PR TITLE
We now have a fedoraproject.org Matrix

### PR DESCRIPTION
**Pull request by ericcurtin**
For people to reach out

### CODE REVIEW

**Comment by ericcurtin** [comment]
Do we want to announce in the Discord that Matrix will become the primary place for collaboration... Or just leave things be organically?

**Comment by rhatdan** [comment]
Can we link them together?

**Comment by ericcurtin** [comment]
I think @smooge said we can't, but just tagging him to confirm

**Comment by smooge** [comment]
In order to link them someone needs to run and maintain a bridge server. It can turn into a full time job

**Comment by rhatdan** [comment]
@smooge so you think we should just move to Matrix and drop Discord?

**Pull request merged**
