### PR TITLE
multiarch build

### PR DESCRIPTION
**Pull request by cooktheryan**
starting point @ericcurtin we will need to add some secrets to the github actions for logging into quay and where we want to publish this nightlys. 

We could also use this same thing to produce releases when we feel comfortable

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]
LGTM

**Comment by ericcurtin** [comment]
Do you have a quay username @cooktheryan ? Want to give you admin quay access

**Comment by cooktheryan** [comment]
@ericcurtin rcook

**Comment by ericcurtin** [comment]
Gave you admin access on quay there now @cooktheryan https://quay.io/repository/ramalama/ramalama

**Pull request merged**
