### PR TITLE
Allow pushing from one type of AI Image to an OCI Image

### PR DESCRIPTION
**Pull request by rhatdan**
This PR allows users to push images pulled as one type and then push them to an OCI Registry.

For example
ramalama pull tiny
ramalama push tiny quay.io/myregistry/tiny:latest

### CODE REVIEW

**Comment by rhatdan** [comment]
This is WIP because omlmd/oras are currently broken since they do not allow pushing of files with ":" in them.

I opened https://github.com/oras-project/oras-py/pull/161 to move this forward.

**Comment by tarilabs** [comment]
> I opened [oras-project/oras-py#161](https://github.com/oras-project/oras-py/pull/161) to move this forward.

Thank you; I've added some suggestions and consideration to the PR you raised; hope that helps

**Review by ericcurtin — APPROVED** [review]
Don't see any immediate issue here, this is still marked WIP though

**Comment by tarilabs** [comment]
fwiw https://github.com/containers/ramalama/pull/311

**Pull request merged**
