### PR TITLE
On Mac, run in container ...

### PR DESCRIPTION
**Pull request by rhatdan**
if podman is configured with krunkit,

or if Docker is installed.

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by rhatdan** [comment]
Have you built one?  IE Can you push one there?

**Comment by ericcurtin** [comment]
Unfortunately I can't by end of day, would have to set up podman farm

**Comment by ericcurtin** [comment]
We really have to get multi-arch container builds automated

**Comment by ericcurtin** [comment]
Even for contributors, it's not reasonable to expect them to do test builds for multiple CPU arches

**Pull request merged**
