### PR TITLE
Translate into class structure 

### PR DESCRIPTION
**Pull request by rhatdan**
Also changes default TRANSPORT to OCI rather then ollama

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
Will will have to rewrite the README.md also, practically all the examples assume ollama as default

**Comment by ericcurtin** [comment]
We probably need to implement shortnames soon, so we can do OCI equivalents of:

`ramalama run granite-code`

**Comment by ericcurtin** [comment]
I wouldn't mind doing fallbacks either... If oci doesn't work, try ollama, if ollama doesn't work try huggingface... Ollama registry has a decent database of shortname convenient to use models

**Comment by rhatdan** [comment]
We can go back to ollama by default, but since we are trying to get people to OCI, that seems counterproductive.  Bottom line it is a one line change.

The next thing I want to work on is getting bats testing, and adding tests for OCI Registries.

We need to improve CI/CD systems.

We also go to get ollama and huggingface push working.

**Comment by ericcurtin** [comment]
Yeah I agree, there's a few bugs I've found yesterday, more tests would help

**Pull request merged**
