### PR TITLE
Bump to v0.0.20

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by rhatdan** [comment]
I am not sure what is going on with the rpms but I am going to merge.  And then tag a release and see if the test starts passing.

@smooge @lsm5 do you know what is happening?

**Comment by lsm5** [comment]
```
RPM build errors:
    File not found: /builddir/build/BUILDROOT/python-ramalama-0.0.19-1.20241021192157934603.pr349.58.g81f3ad8.fc40.x86_64/usr/lib/python3.12/site-packages/ramalama-0.0.19.dist-info
```

**Comment by lsm5** [comment]
Failed fedora copr builds: https://copr.fedorainfracloud.org/coprs/packit/containers-ramalama-349/build/8163678/ . See the `builder-live.log.gz` against each target.

**Comment by rhatdan** [comment]
I bumped the version in the spec file after cutting the release.  I can bump them again simultaneously to see if this fixes the problem.

**Pull request merged**
