### PR TITLE
Fix handling of ramalama login huggingface

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/ramalama/issues/465

## Summary by Sourcery

Fix the handling of HuggingFace login by refining command execution and model path logic, enhance code clarity with refactored methods, and update garbage collection to include more repository paths.

Bug Fixes:
- Fix the handling of login for HuggingFace models by adjusting the command execution and model path logic.

Enhancements:
- Refactor the model path and existence check methods to improve code clarity and maintainability.
- Update the garbage collection logic to include additional repository paths such as 'file', 'http', and 'https'.
- Standardize the model type naming to lowercase for consistency across the codebase.

### CODE REVIEW

**Comment by rhatdan** [comment]
@bentito  PTAL

**Comment by rhatdan** [comment]
@bmahabirbu @cooktheryan PTAL

**Comment by bentito** [comment]
>  @bentito  PTAL

do you @rhatdan happen to know the pipx command to checkout the pr branch? I can't quite seem to get it right...

**Comment by rhatdan** [comment]
No idea, how to do this.  

I would do a git clone of the repo and then run
./bin/ramalama

**Comment by bmahabirbu** [comment]
> @bmahabirbu @cooktheryan PTAL

Did a quick test and worked for me! 

```
./bin/ramalama login --token=XXX huggingface
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
The token `PC` has been saved to /home/bmahabir/.cache/huggingface/stored_tokens
Your token has been saved to /home/bmahabir/.cache/huggingface/token
Login successful.
The current active token is: `PC`
```

**Comment by bentito** [comment]
I was able to login huggingface thanks!

**Comment by bentito** [comment]
Tried:

```bash
$ ramalama pull --authfile /Users/btofel/.cache/huggingface/token huggingface://ibm-granite/granite-3.0-8b-instruct
Error: failed to pull https://huggingface.co/ibm-granite/raw/main/granite-3.0-8b-instruct: HTTP Error 401: Unauthorized

$ ramalama pull --authfile /Users/btofel/.cache/huggingface/foo huggingface://ibm-granite/granite-3.0-8b-instruct
Error: failed to pull https://huggingface.co/ibm-granite/raw/main/granite-3.0-8b-instruct: HTTP Error 401: Unauthorized
```

if the token is supposed to be referenced as the authfile, I'm not sure it's checking that b/c it doesn't seem to care if it doesn't exist.

**Comment by rhatdan** [comment]
@bentito I have never worked with the hugginface login to pull images, so I don't know if this works, but I would love to work with you to make it work.  Could you ping me on the matrix channel.

**Pull request merged**
