### PR TITLE
Pass ASAHI, CUDA, HIP, HSA prefixed env vars to container

### PR DESCRIPTION
**Pull request by abn**
Relates-to: #525

## Summary by Sourcery

Build:
- Pass environment variables prefixed with ASAHI, CUDA, HIP, and HSA to the container via `get_env_vars`.

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
I think this is fine, but we have to be mindful of the generators for Quadlet, etc. to ensure the env vars get taken into account there also

**Comment by abn** [comment]
I will push up a change to include those as well.

**Comment by abn** [comment]
@ericcurtin I am curious however, if the better change is to enable explicit `--env | -e` option for the `serve` command instead. But if the generated files are always expected to be used on the local machine, this should be fine I reckon.

**Comment by abn** [comment]
@sourcery-ai review

**Review by ericcurtin — APPROVED** [review]

**Pull request merged**
