### PR TITLE
Share these paths if they exist

### PR DESCRIPTION
**Pull request by ericcurtin**
For config

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
But needs a rebase.

**Comment by rhatdan** [comment]
This PR is going to conflict with my big PR to move away from python inside of the container.

**Comment by ericcurtin** [comment]
Feel free to ignore, if we move to the model where we try to only run llama.cpp/vllm in the container this code becomes irrelevant

**Comment by rhatdan** [comment]
Needs a rebase.

**Pull request closed without merging**
