### PR TITLE
Docu

### PR DESCRIPTION
**Pull request by atarlov**
- correct docu 
in the logout section it is huggingface

## Summary by Sourcery

Documentation:
- Correct the documentation in the logout section to accurately reflect the login command for the huggingface registry.

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @atarlov 
You need to sign your commit.

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Thanks @atarlov. Love to hear your feedback on the project. What would you like to see added?

**Comment by atarlov** [comment]
hi @rhatdan,  i found the project two days ago and have some use cases in mind. I am working on an infra/network automation platform based on rhel/podman/ansible/python and ramalama could quite good fit. I will drop a feedback after some tests

**Comment by rhatdan** [comment]
Awesome, we can use all the help we can get.

**Pull request merged**
