### PR TITLE
Packit: Initial enablement

### PR DESCRIPTION
**Pull request by lsm5**
Most of this was copied from podman-py package.

### CODE REVIEW

**Comment by lsm5** [comment]
@rhatdan @ericcurtin do you want to allow people to install bleeding-edge builds of this soon after upstream merge? And would you be ok with hosting these bleeding edge builds on [rhcontainerbot/podman-next](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/packages/) or would you prefer a separate copr?

**Comment by lsm5** [comment]
@rhatdan @ericcurtin PTAL. To try out the packit builds:

```
sudo dnf -y copr enable packit/containers-ramalama-152
sudo dnf -y install python3-ramalama
```

This worked for me:
```
$ python3
Python 3.13.0rc2 (main, Sep  7 2024, 00:00:00) [GCC 14.2.1 20240905 (Red Hat 14.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ramalama
>>> 
```

**Comment by rhatdan** [comment]
Yes bleeding edge would be good and under podman is fine.
LGTM

**Comment by lsm5** [comment]
building on podman-next at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/8027725/

**Pull request merged**
